<?php
/**
 * Extended demo network — the complete screen inventory.
 *
 * Adds every remaining placement from the national inventory:
 * all Police Plaza and Gulshan Circle faces, the Dhanmondi/New Market
 * belt, Mohakhali cluster, Old Dhaka, and the full regional network
 * (Sylhet points, Rangpur, Bogura, Narayanganj, Feni indoor).
 *
 * @package Bangla_LED
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Additional city → neighborhood terms.
 *
 * @return array<string, string[]>
 */
function bangla_led_demo_terms_extra() {
	return array(
		'Dhaka'       => array( 'Farmgate', 'Hatirpool', 'Panthapath', 'Green Road', 'Elephant Road', 'Airport Road', 'Sadarghat' ),
		'Chattogram'  => array( 'Station Road' ),
		'Sylhet'      => array( 'Uposohor', 'Nairpul', 'Chowkideki', 'Rikabi Bazar', 'Jitu Miah Point', 'Surma Point', 'Tilaghar' ),
		'Rajshahi'    => array( 'New Market' ),
		'Rangpur'     => array( 'Shapla Mor' ),
		'Bogura'      => array( 'Circuit House' ),
		'Narayanganj' => array( 'Chashara' ),
		'Feni'        => array( 'Feni City' ),
	);
}

/**
 * The extended placements.
 *
 * @return array[]
 */
function bangla_led_demo_locations_extra() {
	return array(

		/* ---- Police Plaza complex (Gulshan) ---- */
		array(
			'title'    => 'Police Plaza, Gulshan-1 Facing',
			'city'     => 'Dhaka',
			'hood'     => 'Gulshan',
			'featured' => '',
			'excerpt'  => 'The Police Plaza face that reads to Gulshan-1 — premium mall footfall and circle-bound executive traffic in one frame.',
			'content'  => "<p>While the south face talks to Hatirjheel, this screen addresses the traffic flowing toward Gulshan Circle-1 — shoppers entering the mall, executives leaving the diplomatic zone, and the steady churn of premium ride-share traffic between the two circles.</p><p>Pair it with the south face for full 360° ownership of Dhaka's most valuable mall frontage.</p>",
			'meta'     => array(
				'_bl_impressions'   => '135,000+',
				'_bl_total_traffic' => '4M+ / month',
				'_bl_gender_split'  => '58% Male / 42% Female',
				'_bl_age_groups'    => '25–44 core (62%)',
				'_bl_professions'   => 'Executives, Premium Shoppers',
				'_bl_exposure'      => '5–8 plays / stop',
				'_bl_facing'        => 'Gulshan Circle-1 Approach',
				'_bl_demographic'   => 'Mall & Corporate Traffic',
				'_bl_dimensions'    => "20' x 10'",
				'_bl_resolution'    => 'P5 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '10:00–13:00 / 17:00–21:00',
				'_bl_dwell_time'    => '75+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Mall Frontage Screen',
				'_bl_lat'           => '23.7809',
				'_bl_lng'           => '90.4150',
			),
		),
		array(
			'title'    => 'Police Plaza Front Side',
			'city'     => 'Dhaka',
			'hood'     => 'Gulshan',
			'featured' => '',
			'excerpt'  => "The marquee face of Police Plaza Concord — straight down the entrance axis where every visitor's eyes land first.",
			'content'  => "<p>The front-side screen owns the plaza's main visual axis: every vehicle entering the complex, every pedestrian crossing toward the mall, and the queued traffic on the frontage road read this face by default.</p><p>Retail launches and brand-theatre creative perform best here — this is the screen the audience is already walking toward.</p>",
			'meta'     => array(
				'_bl_impressions'   => '125,000+',
				'_bl_total_traffic' => '3.75M+ / month',
				'_bl_gender_split'  => '56% Male / 44% Female',
				'_bl_age_groups'    => '18–44 core (66%)',
				'_bl_professions'   => 'Shoppers, Executives, Families',
				'_bl_exposure'      => '5–7 plays / stop',
				'_bl_facing'        => 'Plaza Entrance Axis',
				'_bl_demographic'   => 'Premium Retail Footfall',
				'_bl_dimensions'    => "20' x 12'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '11:00–14:00 / 17:00–21:30',
				'_bl_dwell_time'    => '70+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Entrance Axis Screen',
				'_bl_lat'           => '23.7805',
				'_bl_lng'           => '90.4147',
			),
		),
		array(
			'title'    => 'Police Plaza Entry Gate, South',
			'city'     => 'Dhaka',
			'hood'     => 'Gulshan',
			'featured' => '',
			'excerpt'  => 'Point-blank exposure at the southern entry of Police Plaza — the last message shoppers see before they spend.',
			'content'  => "<p>Gate screens convert. Positioned at the southern entry, this display catches every visitor at walking speed, at eye level, seconds before purchase decisions happen inside.</p><p>Retail, F&amp;B, and financial-services offers earn direct response here — the shortest distance between an impression and a transaction anywhere on the network.</p>",
			'meta'     => array(
				'_bl_impressions'   => '60,000+ footfall',
				'_bl_total_traffic' => '1.8M+ / month',
				'_bl_gender_split'  => '52% Male / 48% Female',
				'_bl_age_groups'    => '18–44 core (70%)',
				'_bl_professions'   => 'Shoppers, Diners, Families',
				'_bl_exposure'      => 'Eye-level walk-past, 100% notice',
				'_bl_facing'        => 'South Entry Walkway',
				'_bl_demographic'   => 'Purchase-Ready Shoppers',
				'_bl_dimensions'    => "12' x 8'",
				'_bl_resolution'    => 'P5 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '12:00–15:00 / 17:00–21:30',
				'_bl_dwell_time'    => '15+ seconds walk-past',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Gate-Level Conversion Screen',
				'_bl_lat'           => '23.7803',
				'_bl_lng'           => '90.4145',
			),
		),
		array(
			'title'    => 'Police Plaza Entry Gate, North',
			'city'     => 'Dhaka',
			'hood'     => 'Gulshan',
			'featured' => '',
			'excerpt'  => 'The northern gate twin — completing point-of-entry coverage of Police Plaza Concord.',
			'content'  => "<p>The northern counterpart to the south gate screen, covering visitors arriving from the Gulshan-1 side. Together the pair guarantees that no one enters the complex without passing your creative at conversation distance.</p><p>Book both gates with an exterior face and your brand frames the entire shopping journey — approach, arrival, and purchase.</p>",
			'meta'     => array(
				'_bl_impressions'   => '55,000+ footfall',
				'_bl_total_traffic' => '1.65M+ / month',
				'_bl_gender_split'  => '53% Male / 47% Female',
				'_bl_age_groups'    => '18–44 core (69%)',
				'_bl_professions'   => 'Shoppers, Office Staff, Families',
				'_bl_exposure'      => 'Eye-level walk-past, 100% notice',
				'_bl_facing'        => 'North Entry Walkway',
				'_bl_demographic'   => 'Purchase-Ready Shoppers',
				'_bl_dimensions'    => "12' x 8'",
				'_bl_resolution'    => 'P5 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '12:00–15:00 / 17:00–21:30',
				'_bl_dwell_time'    => '15+ seconds walk-past',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Gate-Level Conversion Screen',
				'_bl_lat'           => '23.7810',
				'_bl_lng'           => '90.4148',
			),
		),

		/* ---- Gulshan circles, remaining faces ---- */
		array(
			'title'    => 'Gulshan Circle-1 Mid Island, Twin Screens',
			'city'     => 'Dhaka',
			'hood'     => 'Gulshan',
			'featured' => '',
			'excerpt'  => 'Two synchronised island screens at the centre of Gulshan-1 — one faces Gulshan-2 and Mohakhali, the other Police Plaza. Nothing circles past unseen.',
			'content'  => "<p>Planted on the circle's central island, this twin installation reads in both directions at once: one face addresses traffic from Gulshan-2 and Mohakhali, the other the Police Plaza approach. Every rotation of the roundabout is a fresh exposure.</p><p>The island position means zero obstruction at windshield height — the screens sit exactly where stopped drivers stare.</p>",
			'meta'     => array(
				'_bl_impressions'   => '155,000+',
				'_bl_total_traffic' => '4.65M+ / month',
				'_bl_gender_split'  => '60% Male / 40% Female',
				'_bl_age_groups'    => '25–44 core (59%)',
				'_bl_professions'   => 'Executives, Agency Staff, Retail Buyers',
				'_bl_exposure'      => '5–8 plays / stop (2 faces)',
				'_bl_facing'        => 'Gulshan-2/Mohakhali & Police Plaza',
				'_bl_demographic'   => 'Affluent Circle Traffic',
				'_bl_dimensions'    => "2 × 20' x 10'",
				'_bl_resolution'    => 'P5 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '09:00–12:00 / 17:00–20:00',
				'_bl_dwell_time'    => '75+ seconds',
				'_bl_hours'         => '9h Daily',
				'_bl_traffic_note'  => 'Centre-Island Twin Faces',
				'_bl_lat'           => '23.7807',
				'_bl_lng'           => '90.4168',
			),
		),
		array(
			'title'    => 'Gulshan Circle-2 West Side, Barun Bhaban',
			'city'     => 'Dhaka',
			'hood'     => 'Gulshan',
			'featured' => '',
			'excerpt'  => "A 30'×15' face reading to Baridhara and Notun Bazar — the diplomatic quarter's inbound message board.",
			'content'  => "<p>Mounted on Barun Bhaban's west elevation, this screen addresses traffic arriving from Baridhara's embassy row and the Notun Bazar corridor — diplomats, development-sector leadership, and the international school run.</p><p>Thirteen daily hours of operation cover the full diplomatic working day, plus the evening restaurant traffic that defines Gulshan-2 after dark.</p>",
			'meta'     => array(
				'_bl_impressions'   => '130,000+',
				'_bl_total_traffic' => '3.9M+ / month',
				'_bl_gender_split'  => '57% Male / 43% Female',
				'_bl_age_groups'    => '25–54 core (63%)',
				'_bl_professions'   => 'Diplomats, NGO Leadership, Expats',
				'_bl_exposure'      => '5–7 plays / stop',
				'_bl_facing'        => 'Baridhara & Notun Bazar',
				'_bl_demographic'   => 'Diplomatic Corridor Traffic',
				'_bl_dimensions'    => "30' x 15'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '08:30–11:00 / 17:00–22:00',
				'_bl_dwell_time'    => '70+ seconds',
				'_bl_hours'         => '13h Daily',
				'_bl_traffic_note'  => 'Embassy Row Inbound',
				'_bl_lat'           => '23.7948',
				'_bl_lng'           => '90.4138',
			),
		),
		array(
			'title'    => 'Gulshan Circle-2 North Side, Lower Screen',
			'city'     => 'Dhaka',
			'hood'     => 'Gulshan',
			'featured' => '',
			'excerpt'  => "Windshield-height impact on the Gulshan-1 approach — the low-mounted screen drivers can't look over.",
			'content'  => "<p>Most circle screens sit high; this one sits low — directly in the sightline of drivers queued on the Gulshan-1 approach. At 28 feet wide and windshield height, it fills the view rather than decorating it.</p><p>Fourteen operating hours make it a workhorse for sustained-frequency campaigns in the premium zone.</p>",
			'meta'     => array(
				'_bl_impressions'   => '140,000+',
				'_bl_total_traffic' => '4.2M+ / month',
				'_bl_gender_split'  => '59% Male / 41% Female',
				'_bl_age_groups'    => '25–44 core (61%)',
				'_bl_professions'   => 'Executives, Retail Staff, Residents',
				'_bl_exposure'      => '6–8 plays / stop',
				'_bl_facing'        => 'Gulshan-1 Approach',
				'_bl_demographic'   => 'Premium Zone Commuters',
				'_bl_dimensions'    => "28' x 15'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '08:00–11:00 / 17:00–22:00',
				'_bl_dwell_time'    => '80+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Eye-Level Queue Screen',
				'_bl_lat'           => '23.7950',
				'_bl_lng'           => '90.4144',
			),
		),
		array(
			'title'    => 'Gulshan Circle-2 East Side, Amanullah Trade Center',
			'city'     => 'Dhaka',
			'hood'     => 'Gulshan',
			'featured' => '',
			'excerpt'  => 'The fourth face of Gulshan-2 — completing total visual ownership of the circle from the Amanullah Trade Center elevation.',
			'content'  => "<p>The Amanullah Trade Center face closes the loop on Gulshan Circle-2: with the Grand Face, Barun Bhaban, and the north lower screen, all four approaches to the diplomatic zone's busiest roundabout now carry the network.</p><p>Brands booking the full circle get something no static site can sell — the audience literally cannot enter Gulshan-2 without meeting the campaign.</p>",
			'meta'     => array(
				'_bl_impressions'   => '120,000+',
				'_bl_total_traffic' => '3.6M+ / month',
				'_bl_gender_split'  => '58% Male / 42% Female',
				'_bl_age_groups'    => '25–44 core (60%)',
				'_bl_professions'   => 'Corporate Staff, Shoppers, Expats',
				'_bl_exposure'      => '5–7 plays / stop',
				'_bl_facing'        => 'Circle East Approach',
				'_bl_demographic'   => 'Diplomatic Zone Traffic',
				'_bl_dimensions'    => "24' x 12'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '08:30–11:00 / 17:00–21:30',
				'_bl_dwell_time'    => '70+ seconds',
				'_bl_hours'         => '13h Daily',
				'_bl_traffic_note'  => 'Circle Completion Face',
				'_bl_lat'           => '23.7943',
				'_bl_lng'           => '90.4152',
			),
		),

		/* ---- Farmgate / parliament belt ---- */
		array(
			'title'    => 'Manik Mia Avenue, Aarong Signal',
			'city'     => 'Dhaka',
			'hood'     => 'Farmgate',
			'featured' => '',
			'excerpt'  => "Parliament's front lawn meets retail's favourite signal — institutional gravitas with shopping-corridor dwell.",
			'content'  => "<p>Manik Mia Avenue carries the country's political and administrative traffic past one of its best-known retail anchors. The Aarong signal holds that audience — ministers' convoys, civil servants, and brand-conscious shoppers — in a long, reliable queue.</p><p>Few placements combine institutional weight and consumer intent this neatly.</p>",
			'meta'     => array(
				'_bl_impressions'   => '125,000+',
				'_bl_total_traffic' => '3.75M+ / month',
				'_bl_gender_split'  => '61% Male / 39% Female',
				'_bl_age_groups'    => '25–54 core (62%)',
				'_bl_professions'   => 'Civil Servants, Shoppers, Professionals',
				'_bl_exposure'      => '6–8 plays / stop',
				'_bl_facing'        => 'Parliament Axis & Aarong Front',
				'_bl_demographic'   => 'Administrative & Retail Traffic',
				'_bl_dimensions'    => "24' x 12'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '09:00–11:30 / 16:30–20:30',
				'_bl_dwell_time'    => '85+ seconds',
				'_bl_hours'         => '15h Daily',
				'_bl_traffic_note'  => 'Signalised Retail Anchor',
				'_bl_lat'           => '23.7593',
				'_bl_lng'           => '90.3788',
			),
		),
		array(
			'title'    => 'Khamar Bari Moor',
			'city'     => 'Dhaka',
			'hood'     => 'Farmgate',
			'featured' => '',
			'excerpt'  => "Farmgate's pressure valve — 165,000+ daily movements where the city's busiest bus corridor meets the parliament zone.",
			'content'  => "<p>Khamar Bari junction routes Farmgate's enormous commuter volume — one of the highest pedestrian-plus-vehicle counts in the capital — between the bus corridor, the parliament zone, and the Tejgaon office belt.</p><p>For mass-reach campaigns that still want a professional skew, this moor delivers tonnage with substance.</p>",
			'meta'     => array(
				'_bl_impressions'   => '165,000+',
				'_bl_total_traffic' => '4.95M+ / month',
				'_bl_gender_split'  => '64% Male / 36% Female',
				'_bl_age_groups'    => '18–44 core (67%)',
				'_bl_professions'   => 'Commuters, Students, Office Staff',
				'_bl_exposure'      => '5–8 plays / stop',
				'_bl_facing'        => 'Farmgate & Khamar Bari Axis',
				'_bl_demographic'   => 'Mass Commuter Flow',
				'_bl_dimensions'    => "20' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '07:30–10:30 / 16:30–21:00',
				'_bl_dwell_time'    => '70+ seconds',
				'_bl_hours'         => '15h Daily',
				'_bl_traffic_note'  => 'High-Volume Junction',
				'_bl_lat'           => '23.7585',
				'_bl_lng'           => '90.3838',
			),
		),

		/* ---- Hatirpool / Panthapath / Green Road / Elephant Road ---- */
		array(
			'title'    => 'Eastern Plaza, Hatirpool',
			'city'     => 'Dhaka',
			'hood'     => 'Hatirpool',
			'featured' => '',
			'excerpt'  => "The electronics-retail landmark of Sonargaon Road — tech buyers and central Dhaka's through-traffic in one frame.",
			'content'  => "<p>Eastern Plaza has meant gadgets to Dhaka for a generation. Its screen addresses the Sonargaon Road flow between Karwan Bazar and Science Lab — a corridor thick with tech-intent shoppers, students, and central-city commuters.</p><p>Device, telecom, and electronics-finance brands are effectively advertising at their own category's front door.</p>",
			'meta'     => array(
				'_bl_impressions'   => '120,000+',
				'_bl_total_traffic' => '3.6M+ / month',
				'_bl_gender_split'  => '63% Male / 37% Female',
				'_bl_age_groups'    => '18–34 core (64%)',
				'_bl_professions'   => 'Tech Buyers, Students, Commuters',
				'_bl_exposure'      => '5–7 plays / stop',
				'_bl_facing'        => 'Sonargaon Road Both Flows',
				'_bl_demographic'   => 'Tech-Intent Shoppers',
				'_bl_dimensions'    => "18' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '11:00–14:00 / 16:00–20:30',
				'_bl_dwell_time'    => '60+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Category Landmark Screen',
				'_bl_lat'           => '23.7459',
				'_bl_lng'           => '90.3917',
			),
		),
		array(
			'title'    => 'Bashundhara City Indoor Network',
			'city'     => 'Dhaka',
			'hood'     => 'Panthapath',
			'featured' => '',
			'excerpt'  => "Inside South Asia's iconic mega-mall — climate-controlled attention from 80,000+ daily visitors who came to spend.",
			'content'  => "<p>Bashundhara City's indoor screens reach an audience no roadside billboard can promise: people who have already parked, already planned to spend, and move at browsing speed past every display.</p><p>Fashion, electronics, F&amp;B, and financial-services offers convert here because the distance from impression to till is an escalator ride.</p>",
			'meta'     => array(
				'_bl_impressions'   => '80,000+ footfall',
				'_bl_total_traffic' => '2.4M+ / month',
				'_bl_gender_split'  => '51% Male / 49% Female',
				'_bl_age_groups'    => '18–44 core (72%)',
				'_bl_professions'   => 'Shoppers, Families, Students',
				'_bl_exposure'      => 'Continuous browse-speed exposure',
				'_bl_facing'        => 'Mall Atrium & Concourse',
				'_bl_demographic'   => 'Purchase-Ready Mall Visitors',
				'_bl_dimensions'    => 'Indoor Concourse Array',
				'_bl_resolution'    => 'P4 Indoor',
				'_bl_brightness'    => '1,200 nits (indoor)',
				'_bl_peak_hours'    => '12:00–21:00',
				'_bl_dwell_time'    => 'Browse-speed footfall',
				'_bl_hours'         => '12h Daily',
				'_bl_traffic_note'  => 'Indoor Mall Network',
				'_bl_lat'           => '23.7507',
				'_bl_lng'           => '90.3902',
			),
		),
		array(
			'title'    => 'Green Road Crossing, U-Turn',
			'city'     => 'Dhaka',
			'hood'     => 'Green Road',
			'featured' => '',
			'excerpt'  => 'The slow-motion U-turn every Green Road driver knows — guaranteed low-speed, screen-facing exposure.',
			'content'  => "<p>U-turns are the unsung heroes of outdoor media: traffic decelerates, turns toward the screen, and crawls past it nose-first. The Green Road crossing adds hospital, university, and residential flows to that geometry.</p><p>Healthcare, education, and family brands get unusually attentive exposure at an honest price point.</p>",
			'meta'     => array(
				'_bl_impressions'   => '105,000+',
				'_bl_total_traffic' => '3.15M+ / month',
				'_bl_gender_split'  => '58% Male / 42% Female',
				'_bl_age_groups'    => '18–44 core (65%)',
				'_bl_professions'   => 'Medical Staff, Students, Residents',
				'_bl_exposure'      => '4–6 plays / turn cycle',
				'_bl_facing'        => 'U-Turn Approach, Both Flows',
				'_bl_demographic'   => 'Residential & Medical Corridor',
				'_bl_dimensions'    => "16' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '08:00–11:00 / 16:00–20:30',
				'_bl_dwell_time'    => '50+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Screen-Facing U-Turn',
				'_bl_lat'           => '23.7480',
				'_bl_lng'           => '90.3850',
			),
		),
		array(
			'title'    => 'Bata Signal, Elephant Road',
			'city'     => 'Dhaka',
			'hood'     => 'Elephant Road',
			'featured' => '',
			'excerpt'  => "Dhaka's footwear-and-fashion mile at its busiest point — young, trend-driven, and stopped at your screen.",
			'content'  => "<p>Elephant Road is where Dhaka's students and young professionals shop on real budgets, and the Bata signal is its choke point. The audience skews 18–34, fashion-aware, and price-sharp.</p><p>Youth brands, devices, and fast fashion get exactly the eyes they pay for — at the exact moment those eyes are shopping.</p>",
			'meta'     => array(
				'_bl_impressions'   => '115,000+',
				'_bl_total_traffic' => '3.45M+ / month',
				'_bl_gender_split'  => '57% Male / 43% Female',
				'_bl_age_groups'    => '18–34 core (73%)',
				'_bl_professions'   => 'Students, Young Professionals',
				'_bl_exposure'      => '5–7 plays / stop',
				'_bl_facing'        => 'Elephant Road & New Market Axis',
				'_bl_demographic'   => 'Youth Retail Traffic',
				'_bl_dimensions'    => "16' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '11:00–14:00 / 16:00–21:00',
				'_bl_dwell_time'    => '65+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Youth Retail Signal',
				'_bl_lat'           => '23.7390',
				'_bl_lng'           => '90.3858',
			),
		),

		/* ---- Dhanmondi belt, remaining ---- */
		array(
			'title'    => 'Dhanmondi 27 Mid Island',
			'city'     => 'Dhaka',
			'hood'     => 'Dhanmondi',
			'featured' => '',
			'excerpt'  => 'The island twin on Mirpur Road at Dhanmondi 27 — double-direction coverage of the high street junction.',
			'content'  => "<p>Where the Rapa Plaza face reads one flow, the mid-island screen reads both: northbound and southbound Mirpur Road traffic meet it at the centre of the junction, windshield-height and unmissable.</p><p>Booked together with the Rapa Plaza face, the pair owns Dhanmondi 27 outright.</p>",
			'meta'     => array(
				'_bl_impressions'   => '125,000+',
				'_bl_total_traffic' => '3.75M+ / month',
				'_bl_gender_split'  => '55% Male / 45% Female',
				'_bl_age_groups'    => '18–44 core (65%)',
				'_bl_professions'   => 'Families, Students, Professionals',
				'_bl_exposure'      => '5–7 plays / stop (both flows)',
				'_bl_facing'        => 'Mirpur Road, Both Directions',
				'_bl_demographic'   => 'Affluent Residential Traffic',
				'_bl_dimensions'    => "18' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '10:00–13:00 / 17:00–21:30',
				'_bl_dwell_time'    => '65+ seconds',
				'_bl_hours'         => '15h Daily',
				'_bl_traffic_note'  => 'Centre-Island Twin Flow',
				'_bl_lat'           => '23.7563',
				'_bl_lng'           => '90.3745',
			),
		),
		array(
			'title'    => 'Dhanmondi 2 Gate',
			'city'     => 'Dhaka',
			'hood'     => 'Dhanmondi',
			'featured' => '',
			'excerpt'  => "The quieter, wealthier end of Dhanmondi — school-run families, lakeside residents, and the city's old establishment.",
			'content'  => "<p>Dhanmondi 2 serves the neighbourhood's residential heart: heritage families, the lakeside leisure circuit, and one of the densest school clusters in the city. The audience is smaller than Road 27 — and noticeably wealthier per head.</p><p>Premium education, healthcare, and family-finance brands find their exact customer at this gate.</p>",
			'meta'     => array(
				'_bl_impressions'   => '95,000+',
				'_bl_total_traffic' => '2.85M+ / month',
				'_bl_gender_split'  => '53% Male / 47% Female',
				'_bl_age_groups'    => '25–54 core (61%)',
				'_bl_professions'   => 'Established Families, Educators',
				'_bl_exposure'      => '4–6 plays / stop',
				'_bl_facing'        => 'Road 2 & Lake Circuit',
				'_bl_demographic'   => 'Heritage Residential Wealth',
				'_bl_dimensions'    => "16' x 9'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '07:30–09:30 / 16:00–20:00',
				'_bl_dwell_time'    => '55+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'School-Run Corridor',
				'_bl_lat'           => '23.7406',
				'_bl_lng'           => '90.3768',
			),
		),
		array(
			'title'    => 'City College Circle',
			'city'     => 'Dhaka',
			'hood'     => 'Dhanmondi',
			'featured' => '',
			'excerpt'  => "Sixty thousand students a day, one circle — the youth-density record holder of the Dhanmondi education belt.",
			'content'  => "<p>City College Circle compresses the education belt's foot and vehicle traffic into a single signalised crossing. The audience is overwhelmingly 16–28, device-native, and forming the brand loyalties they'll carry for decades.</p><p>Telecom packages, devices, ed-tech, and youth finance launch here when they're serious about Gen Z.</p>",
			'meta'     => array(
				'_bl_impressions'   => '145,000+',
				'_bl_total_traffic' => '4.35M+ / month',
				'_bl_gender_split'  => '56% Male / 44% Female',
				'_bl_age_groups'    => '16–28 core (74%)',
				'_bl_professions'   => 'Students, Educators, Young Workers',
				'_bl_exposure'      => '6–8 plays / stop',
				'_bl_facing'        => 'Mirpur Road & College Front',
				'_bl_demographic'   => 'Student-Dense Crossing',
				'_bl_dimensions'    => "18' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '08:00–11:00 / 15:00–19:00',
				'_bl_dwell_time'    => '75+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Education Belt Crossing',
				'_bl_lat'           => '23.7395',
				'_bl_lng'           => '90.3835',
			),
		),
		array(
			'title'    => 'Shimanto Square, Six-Screen Array',
			'city'     => 'Dhaka',
			'hood'     => 'Dhanmondi',
			'featured' => '',
			'excerpt'  => 'Six synchronised screens wrapping one retail landmark — the most immersive single-site takeover in Dhanmondi.',
			'content'  => "<p>Shimanto Square's six-screen array turns a media buy into an environment: synchronised creative wraps the complex, repeating and reinforcing from every approach and every storey.</p><p>Launches that need to feel like events — not ads — book the full array and own the square for the night.</p>",
			'meta'     => array(
				'_bl_impressions'   => '135,000+',
				'_bl_total_traffic' => '4M+ / month',
				'_bl_gender_split'  => '54% Male / 46% Female',
				'_bl_age_groups'    => '18–44 core (69%)',
				'_bl_professions'   => 'Shoppers, Students, Families',
				'_bl_exposure'      => 'Multi-angle, 6-screen synchronised',
				'_bl_facing'        => 'All Approaches, Six Faces',
				'_bl_demographic'   => 'Retail & Leisure Footfall',
				'_bl_dimensions'    => '6-Screen Array',
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '11:00–14:00 / 16:00–21:30',
				'_bl_dwell_time'    => '70+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Synchronised Site Takeover',
				'_bl_lat'           => '23.7378',
				'_bl_lng'           => '90.3792',
			),
		),
		array(
			'title'    => 'Science Lab, Labaid Hospital Front',
			'city'     => 'Dhaka',
			'hood'     => 'Dhanmondi',
			'featured' => '',
			'excerpt'  => "Directly facing the country's best-known private hospital — healthcare's most precise outdoor placement.",
			'content'  => "<p>Thousands of patients, families, and physicians pass Labaid's front every day with health explicitly on their minds. This screen meets that intent head-on.</p><p>Hospitals, diagnostics, pharma OTC, and health-insurance brands get context no other billboard in Bangladesh can offer — the right message at the literal point of care.</p>",
			'meta'     => array(
				'_bl_impressions'   => '110,000+',
				'_bl_total_traffic' => '3.3M+ / month',
				'_bl_gender_split'  => '55% Male / 45% Female',
				'_bl_age_groups'    => '25–64 core (66%)',
				'_bl_professions'   => 'Patients, Physicians, Families',
				'_bl_exposure'      => '5–7 plays / stop',
				'_bl_facing'        => 'Labaid Front & Mirpur Road',
				'_bl_demographic'   => 'Health-Intent Audience',
				'_bl_dimensions'    => "16' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '08:00–12:00 / 16:00–20:00',
				'_bl_dwell_time'    => '70+ seconds',
				'_bl_hours'         => '15h Daily',
				'_bl_traffic_note'  => 'Healthcare Context Screen',
				'_bl_lat'           => '23.7392',
				'_bl_lng'           => '90.3822',
			),
		),

		/* ---- Mohakhali cluster, remaining ---- */
		array(
			'title'    => 'Mohakhali Rail Crossing',
			'city'     => 'Dhaka',
			'hood'     => 'Mohakhali',
			'featured' => '',
			'excerpt'  => 'When the gates drop, the audience stops — minutes of guaranteed dwell at one of the busiest level crossings in the country.',
			'content'  => "<p>Every train through Mohakhali hands this screen something money usually can't buy outdoors: a complete standstill. Gates down, engines off, hundreds of windshields pointed at the display for minutes at a time, dozens of times a day.</p><p>Long-form storytelling creative — 30 to 60 seconds — finally has a billboard built for it.</p>",
			'meta'     => array(
				'_bl_impressions'   => '150,000+',
				'_bl_total_traffic' => '4.5M+ / month',
				'_bl_gender_split'  => '66% Male / 34% Female',
				'_bl_age_groups'    => '18–44 core (66%)',
				'_bl_professions'   => 'Commuters, Corporate Staff, Drivers',
				'_bl_exposure'      => 'Full-loop plays at every gate-down',
				'_bl_facing'        => 'Rail Gate Queue, Both Sides',
				'_bl_demographic'   => 'Captive Crossing Audience',
				'_bl_dimensions'    => "20' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '08:00–11:00 / 17:00–21:00',
				'_bl_dwell_time'    => '3–6 minutes at gate-down',
				'_bl_hours'         => '16h Daily',
				'_bl_traffic_note'  => 'Level-Crossing Standstill',
				'_bl_lat'           => '23.7770',
				'_bl_lng'           => '90.4015',
			),
		),
		array(
			'title'    => 'SKS Tower Exit Gate, Mohakhali',
			'city'     => 'Dhaka',
			'hood'     => 'Mohakhali',
			'featured' => '',
			'excerpt'  => 'The goodbye screen of the SKS retail complex — last impression before purchase-fresh shoppers rejoin the city.',
			'content'  => "<p>Exit screens catch people at a unique moment: purchases made, attention released, and the next decision — where to eat, what to do — wide open. The SKS exit gate owns it.</p><p>F&amp;B, entertainment, and next-visit offers convert this moment better than any roadside face could.</p>",
			'meta'     => array(
				'_bl_impressions'   => '45,000+ footfall',
				'_bl_total_traffic' => '1.35M+ / month',
				'_bl_gender_split'  => '52% Male / 48% Female',
				'_bl_age_groups'    => '18–44 core (71%)',
				'_bl_professions'   => 'Shoppers, Diners, Families',
				'_bl_exposure'      => 'Eye-level walk-past, 100% notice',
				'_bl_facing'        => 'Complex Exit Flow',
				'_bl_demographic'   => 'Post-Purchase Shoppers',
				'_bl_dimensions'    => "10' x 6'",
				'_bl_resolution'    => 'P5 Outdoor',
				'_bl_brightness'    => '4,500 nits',
				'_bl_peak_hours'    => '12:00–15:00 / 17:00–21:00',
				'_bl_dwell_time'    => '12+ seconds walk-past',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Exit-Gate Conversion Screen',
				'_bl_lat'           => '23.7782',
				'_bl_lng'           => '90.4060',
			),
		),
		array(
			'title'    => 'SKS Tower Entrance, Mohakhali',
			'city'     => 'Dhaka',
			'hood'     => 'Mohakhali',
			'featured' => '',
			'excerpt'  => 'First word at the door of the SKS complex — priming every visitor before the shopping starts.',
			'content'  => "<p>The entrance screen sets the agenda: every visitor to the SKS retail and office complex passes it at conversation distance, mindset open, wallet decided but not yet allocated.</p><p>Combined with the exit gate and the flyover face, the SKS trio frames the entire visit — arrival, decision, departure.</p>",
			'meta'     => array(
				'_bl_impressions'   => '50,000+ footfall',
				'_bl_total_traffic' => '1.5M+ / month',
				'_bl_gender_split'  => '53% Male / 47% Female',
				'_bl_age_groups'    => '18–44 core (70%)',
				'_bl_professions'   => 'Shoppers, Office Staff, Visitors',
				'_bl_exposure'      => 'Eye-level walk-past, 100% notice',
				'_bl_facing'        => 'Complex Entrance Flow',
				'_bl_demographic'   => 'Arriving Shoppers & Staff',
				'_bl_dimensions'    => "10' x 6'",
				'_bl_resolution'    => 'P5 Outdoor',
				'_bl_brightness'    => '4,500 nits',
				'_bl_peak_hours'    => '10:00–13:00 / 17:00–20:30',
				'_bl_dwell_time'    => '12+ seconds walk-past',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Entrance Priming Screen',
				'_bl_lat'           => '23.7780',
				'_bl_lng'           => '90.4058',
			),
		),
		array(
			'title'    => 'Hotel Radisson Blu Front, Airport Road',
			'city'     => 'Dhaka',
			'hood'     => 'Airport Road',
			'featured' => '',
			'excerpt'  => "Five-star frontage on the VIP corridor — international guests, business delegations, and the airport's premium flow.",
			'content'  => "<p>The Radisson Blu frontage reads to the most curated audience on Airport Road: arriving delegations, five-star guests, cantonment leadership, and the executive traffic that shuttles between the airport and the diplomatic zone.</p><p>Airlines, luxury, banking, and real-estate brands treat this screen as their handshake with international money.</p>",
			'meta'     => array(
				'_bl_impressions'   => '130,000+',
				'_bl_total_traffic' => '3.9M+ / month',
				'_bl_gender_split'  => '68% Male / 32% Female',
				'_bl_age_groups'    => '30–60 core (63%)',
				'_bl_professions'   => 'International Guests, Executives, Officers',
				'_bl_exposure'      => '4–6 plays / pass',
				'_bl_facing'        => 'Airport Road VIP Corridor',
				'_bl_demographic'   => 'Premium International Flow',
				'_bl_dimensions'    => "24' x 12'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '6,000 nits',
				'_bl_peak_hours'    => '08:00–11:00 / 18:00–23:00',
				'_bl_dwell_time'    => '45+ seconds',
				'_bl_hours'         => '17h Daily',
				'_bl_traffic_note'  => 'Five-Star Frontage',
				'_bl_lat'           => '23.8223',
				'_bl_lng'           => '90.4035',
			),
		),

		/* ---- Old Dhaka ---- */
		array(
			'title'    => 'Sadarghat Launch Terminal',
			'city'     => 'Dhaka',
			'hood'     => 'Sadarghat',
			'featured' => '',
			'excerpt'  => "The river gateway of Bangladesh — hundreds of thousands of launch passengers funnel past one screen.",
			'content'  => "<p>Sadarghat is the busiest river port in the country, and its terminal screen reaches an audience mass media routinely misses: the launch passengers connecting Dhaka to the southern delta, plus Old Dhaka's dense trading economy.</p><p>FMCG, mobile financial services, and remittance brands reach millions of underserved, high-frequency travellers exactly where they wait.</p>",
			'meta'     => array(
				'_bl_impressions'   => '200,000+ footfall',
				'_bl_total_traffic' => '6M+ / month',
				'_bl_gender_split'  => '67% Male / 33% Female',
				'_bl_age_groups'    => '18–54 core (75%)',
				'_bl_professions'   => 'Travellers, Traders, Workers',
				'_bl_exposure'      => 'Extended terminal wait-time',
				'_bl_facing'        => 'Terminal Concourse & Pontoons',
				'_bl_demographic'   => 'River-Route Mass Audience',
				'_bl_dimensions'    => "20' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '06:00–10:00 / 16:00–22:00',
				'_bl_dwell_time'    => '10–40 minutes terminal wait',
				'_bl_hours'         => '16h Daily',
				'_bl_traffic_note'  => 'River Port Terminal',
				'_bl_lat'           => '23.7104',
				'_bl_lng'           => '90.4074',
			),
		),

		/* ---- Chattogram, remaining ---- */
		array(
			'title'    => 'Shohortoli Railway Station Entry, Chattogram',
			'city'     => 'Chattogram',
			'hood'     => 'Station Road',
			'featured' => '',
			'excerpt'  => "The rail gateway of the port city — intercity passengers and Station Road's commercial churn at the entry gate.",
			'content'  => "<p>Every intercity arrival into Chattogram by rail passes this entry-gate screen with luggage in hand and plans wide open — hotels, transport, food, telecom top-ups all decided in the next hour.</p><p>Arrival-moment advertising is the cheapest intent targeting in the business, and this is the port city's arrival moment.</p>",
			'meta'     => array(
				'_bl_impressions'   => '95,000+ footfall',
				'_bl_total_traffic' => '2.85M+ / month',
				'_bl_gender_split'  => '69% Male / 31% Female',
				'_bl_age_groups'    => '18–54 core (72%)',
				'_bl_professions'   => 'Travellers, Traders, Students',
				'_bl_exposure'      => 'Entry-gate walk-past + queue',
				'_bl_facing'        => 'Station Entry Gate',
				'_bl_demographic'   => 'Arriving Intercity Passengers',
				'_bl_dimensions'    => "16' x 9'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '07:00–10:00 / 15:00–20:00',
				'_bl_dwell_time'    => '20+ seconds walk-past',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Rail Arrival Gateway',
				'_bl_lat'           => '22.3360',
				'_bl_lng'           => '91.8123',
			),
		),

		/* ---- Cox's Bazar, remaining ---- */
		array(
			'title'    => "Sughondha Circle, Cox's Bazar",
			'city'     => "Cox's Bazar",
			'hood'     => 'Kolatoli',
			'featured' => '',
			'excerpt'  => 'The roundabout that feeds the beach — every hotel shuttle, tour bus, and family car rotates past this face.',
			'content'  => "<p>One junction up from the beachfront, Sughondha Circle organises the entire hotel zone's traffic. Tour buses, shuttles, and rental cars rotate through it on every trip between room and sand.</p><p>Hospitality and consumer brands use the circle face to multiply frequency on the same holiday audience the beachfront screen reaches.</p>",
			'meta'     => array(
				'_bl_impressions'   => '75,000+ (peak season 130,000+)',
				'_bl_total_traffic' => '2.25M+ / month',
				'_bl_gender_split'  => '56% Male / 44% Female',
				'_bl_age_groups'    => '18–44 core (71%)',
				'_bl_professions'   => 'Tourists, Hotel Staff, Drivers',
				'_bl_exposure'      => '4–6 plays / rotation',
				'_bl_facing'        => 'Hotel Zone Circle, All Approaches',
				'_bl_demographic'   => 'Holiday Traffic Loop',
				'_bl_dimensions'    => "15' x 9'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '09:00–12:00 / 16:00–22:00',
				'_bl_dwell_time'    => '50+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Hotel Zone Roundabout',
				'_bl_lat'           => '21.4185',
				'_bl_lng'           => '91.9820',
			),
		),
		array(
			'title'    => "Dolphin Moor, Cox's Bazar",
			'city'     => "Cox's Bazar",
			'hood'     => 'Kolatoli',
			'featured' => '',
			'excerpt'  => "The Kolatoli landmark every tourist photographs — and the junction every beach trip passes through.",
			'content'  => "<p>Dolphin Moor is the postcard junction of Kolatoli: the sculpture every visitor photographs, at the crossing every beach journey threads through. The screen borrows that landmark gravity.</p><p>Beverage, telecom, and travel brands effectively place themselves inside the holiday photo album of Bangladesh.</p>",
			'meta'     => array(
				'_bl_impressions'   => '70,000+ (peak season 120,000+)',
				'_bl_total_traffic' => '2.1M+ / month',
				'_bl_gender_split'  => '55% Male / 45% Female',
				'_bl_age_groups'    => '18–44 core (72%)',
				'_bl_professions'   => 'Tourists, Families, Drivers',
				'_bl_exposure'      => '4–6 plays / pass',
				'_bl_facing'        => 'Kolatoli Beach Axis',
				'_bl_demographic'   => 'Leisure Landmark Traffic',
				'_bl_dimensions'    => "15' x 9'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,500 nits',
				'_bl_peak_hours'    => '09:00–12:00 / 16:00–22:00',
				'_bl_dwell_time'    => '45+ seconds',
				'_bl_hours'         => '14h Daily',
				'_bl_traffic_note'  => 'Tourist Landmark Junction',
				'_bl_lat'           => '21.4119',
				'_bl_lng'           => '91.9851',
			),
		),

		/* ---- Rajshahi, remaining ---- */
		array(
			'title'    => 'Rajshahi New Market',
			'city'     => 'Rajshahi',
			'hood'     => 'New Market',
			'featured' => '',
			'excerpt'  => "The retail counterweight to Shaheb Bazar — Rajshahi's shopping district at its densest point.",
			'content'  => "<p>New Market concentrates Rajshahi's daily shopping into a few hundred metres, and this screen anchors its busiest face. The audience mixes the university city's students with the divisional capital's trading families.</p><p>Pair it with the Shaheb Bazar twins for complete coverage of where North Bengal actually spends.</p>",
			'meta'     => array(
				'_bl_impressions'   => '85,000+',
				'_bl_total_traffic' => '2.55M+ / month',
				'_bl_gender_split'  => '58% Male / 42% Female',
				'_bl_age_groups'    => '18–44 core (69%)',
				'_bl_professions'   => 'Shoppers, Students, Traders',
				'_bl_exposure'      => '4–6 plays / pass',
				'_bl_facing'        => 'Market Main Approach',
				'_bl_demographic'   => 'Divisional Retail Crowd',
				'_bl_dimensions'    => "15' x 9'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '10:00–13:00 / 16:00–20:30',
				'_bl_dwell_time'    => '55+ seconds',
				'_bl_hours'         => '13h Daily',
				'_bl_traffic_note'  => 'Retail District Anchor',
				'_bl_lat'           => '24.3690',
				'_bl_lng'           => '88.6020',
			),
		),

		/* ---- Sylhet points ---- */
		array(
			'title'    => 'Uposohor Point, Sylhet',
			'city'     => 'Sylhet',
			'hood'     => 'Uposohor',
			'featured' => '',
			'excerpt'  => "Sylhet's planned township — NRB-funded homes, new wealth, and the city's most modern consumer base.",
			'content'  => "<p>Uposohor is where Sylhet's remittance economy builds its houses. The planned township's main point carries the city's newest wealth — returning expatriates, professional families, and the businesses that serve them.</p><p>Banks, MFS, real estate, and consumer durables find their highest-value Sylhet audience on this screen.</p>",
			'meta'     => array(
				'_bl_impressions'   => '90,000+',
				'_bl_total_traffic' => '2.7M+ / month',
				'_bl_gender_split'  => '60% Male / 40% Female',
				'_bl_age_groups'    => '25–54 core (64%)',
				'_bl_professions'   => 'NRB Families, Professionals',
				'_bl_exposure'      => '4–6 plays / stop',
				'_bl_facing'        => 'Township Main Circle',
				'_bl_demographic'   => 'Remittance-Wealth Households',
				'_bl_dimensions'    => "15' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '09:00–12:00 / 16:00–21:00',
				'_bl_dwell_time'    => '55+ seconds',
				'_bl_hours'         => '12h Daily',
				'_bl_traffic_note'  => 'Planned Township Hub',
				'_bl_lat'           => '24.8857',
				'_bl_lng'           => '91.8830',
			),
		),
		array(
			'title'    => 'Nairpul Point, Sylhet',
			'city'     => 'Sylhet',
			'hood'     => 'Nairpul',
			'featured' => '',
			'excerpt'  => "The connector junction of central Sylhet — steady all-day flow between the city's commercial and residential halves.",
			'content'  => "<p>Nairpul stitches Sylhet's commercial core to its residential spread, which gives the screen something rare outside Dhaka: flat, dependable traffic from morning to night rather than two narrow peaks.</p><p>Always-on brands — telecom, beverages, retail banking — get consistent frequency without daypart gaps.</p>",
			'meta'     => array(
				'_bl_impressions'   => '80,000+',
				'_bl_total_traffic' => '2.4M+ / month',
				'_bl_gender_split'  => '62% Male / 38% Female',
				'_bl_age_groups'    => '18–44 core (67%)',
				'_bl_professions'   => 'Commuters, Traders, Families',
				'_bl_exposure'      => '4–6 plays / stop',
				'_bl_facing'        => 'Central Connector Junction',
				'_bl_demographic'   => 'All-Day City Flow',
				'_bl_dimensions'    => "15' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '10:00–21:00 steady',
				'_bl_dwell_time'    => '50+ seconds',
				'_bl_hours'         => '11h Daily',
				'_bl_traffic_note'  => 'Steady-Flow Connector',
				'_bl_lat'           => '24.8917',
				'_bl_lng'           => '91.8736',
			),
		),
		array(
			'title'    => 'Chowkideki Point, Sylhet',
			'city'     => 'Sylhet',
			'hood'     => 'Chowkideki',
			'featured' => '',
			'excerpt'  => "Sylhet's northern gateway circle — the airport-road audience and the tea-belt's daily commerce.",
			'content'  => "<p>Chowkideki organises the northern approach to Sylhet, carrying airport traffic and the tea-estate belt's commercial flow into the city. The audience blends arriving visitors with the established trading families of the north side.</p><p>Hospitality and consumer brands greet Sylhet's guests here first.</p>",
			'meta'     => array(
				'_bl_impressions'   => '75,000+',
				'_bl_total_traffic' => '2.25M+ / month',
				'_bl_gender_split'  => '63% Male / 37% Female',
				'_bl_age_groups'    => '18–54 core (70%)',
				'_bl_professions'   => 'Travellers, Estate Trade, Residents',
				'_bl_exposure'      => '4–6 plays / stop',
				'_bl_facing'        => 'Airport Road Circle',
				'_bl_demographic'   => 'Gateway & Trade Flow',
				'_bl_dimensions'    => "15' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '09:00–12:00 / 16:00–20:00',
				'_bl_dwell_time'    => '50+ seconds',
				'_bl_hours'         => '11h Daily',
				'_bl_traffic_note'  => 'Northern Gateway Circle',
				'_bl_lat'           => '24.9120',
				'_bl_lng'           => '91.8590',
			),
		),
		array(
			'title'    => 'Rikabi Bazar Point, Sylhet',
			'city'     => 'Sylhet',
			'hood'     => 'Rikabi Bazar',
			'featured' => '',
			'excerpt'  => 'The stadium-and-medical-college circle — event-day surges layered on dependable institutional traffic.',
			'content'  => "<p>Rikabi Bazar sits between Sylhet's stadium and its medical college, so the screen earns two audiences: the daily institutional flow of students and health workers, and the periodic surge of match crowds and event traffic.</p><p>Brands time launches to the fixture list and inherit a stadium's worth of attention.</p>",
			'meta'     => array(
				'_bl_impressions'   => '70,000+ (event days 120,000+)',
				'_bl_total_traffic' => '2.1M+ / month',
				'_bl_gender_split'  => '64% Male / 36% Female',
				'_bl_age_groups'    => '16–34 core (69%)',
				'_bl_professions'   => 'Students, Medics, Sports Crowds',
				'_bl_exposure'      => '4–6 plays / stop',
				'_bl_facing'        => 'Stadium & College Circle',
				'_bl_demographic'   => 'Institutional & Event Crowd',
				'_bl_dimensions'    => "15' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '09:00–12:00 / 15:00–20:00',
				'_bl_dwell_time'    => '50+ seconds',
				'_bl_hours'         => '11h Daily',
				'_bl_traffic_note'  => 'Stadium District Circle',
				'_bl_lat'           => '24.9000',
				'_bl_lng'           => '91.8660',
			),
		),
		array(
			'title'    => 'Jitu Miah Point, Sylhet',
			'city'     => 'Sylhet',
			'hood'     => 'Jitu Miah Point',
			'featured' => '',
			'excerpt'  => "Old Sylhet's heritage crossing — the established trading families of the city's historic quarter.",
			'content'  => "<p>Named for one of the city's storied houses, Jitu Miah Point anchors old Sylhet — the historic quarter where the city's longest-standing trading families live and do business.</p><p>Brands that win here win the word-of-mouth networks that still move this market.</p>",
			'meta'     => array(
				'_bl_impressions'   => '65,000+',
				'_bl_total_traffic' => '1.95M+ / month',
				'_bl_gender_split'  => '65% Male / 35% Female',
				'_bl_age_groups'    => '25–64 core (68%)',
				'_bl_professions'   => 'Traders, Heritage Families',
				'_bl_exposure'      => '4–5 plays / stop',
				'_bl_facing'        => 'Heritage Quarter Crossing',
				'_bl_demographic'   => 'Old-City Establishment',
				'_bl_dimensions'    => "15' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '10:00–13:00 / 16:00–20:00',
				'_bl_dwell_time'    => '45+ seconds',
				'_bl_hours'         => '11h Daily',
				'_bl_traffic_note'  => 'Historic Quarter Point',
				'_bl_lat'           => '24.8870',
				'_bl_lng'           => '91.8700',
			),
		),
		array(
			'title'    => 'Surma Point, Sylhet',
			'city'     => 'Sylhet',
			'hood'     => 'Surma Point',
			'featured' => '',
			'excerpt'  => 'The river crossing of Sylhet — Keane Bridge traffic and the south bank funnel into one screen.',
			'content'  => "<p>Everything crossing the Surma — and in Sylhet, eventually everything does — funnels past this point at the Keane Bridge axis. South-bank commuters, river trade, and the tourist circuit to the riverfront all share the queue.</p><p>It's the closest thing Sylhet has to a guaranteed-reach screen.</p>",
			'meta'     => array(
				'_bl_impressions'   => '85,000+',
				'_bl_total_traffic' => '2.55M+ / month',
				'_bl_gender_split'  => '64% Male / 36% Female',
				'_bl_age_groups'    => '18–54 core (72%)',
				'_bl_professions'   => 'Commuters, River Trade, Visitors',
				'_bl_exposure'      => '5–7 plays / stop',
				'_bl_facing'        => 'Keane Bridge Axis',
				'_bl_demographic'   => 'River-Crossing Flow',
				'_bl_dimensions'    => "15' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '08:00–11:00 / 16:00–20:00',
				'_bl_dwell_time'    => '60+ seconds',
				'_bl_hours'         => '11h Daily',
				'_bl_traffic_note'  => 'Bridge Funnel Point',
				'_bl_lat'           => '24.8870',
				'_bl_lng'           => '91.8680',
			),
		),
		array(
			'title'    => 'Tilaghar Point, Sylhet',
			'city'     => 'Sylhet',
			'hood'     => 'Tilaghar',
			'featured' => '',
			'excerpt'  => "The eastern academic gateway — university-bound traffic and Sylhet's growing east-side neighbourhoods.",
			'content'  => "<p>Tilaghar carries the eastern city: the agricultural university's daily population and the fast-growing residential neighbourhoods spreading along the eastern corridor.</p><p>Education, devices, and household brands ride a young, expanding audience that adds households every month.</p>",
			'meta'     => array(
				'_bl_impressions'   => '60,000+',
				'_bl_total_traffic' => '1.8M+ / month',
				'_bl_gender_split'  => '61% Male / 39% Female',
				'_bl_age_groups'    => '16–34 core (70%)',
				'_bl_professions'   => 'Students, Academics, New Households',
				'_bl_exposure'      => '4–5 plays / stop',
				'_bl_facing'        => 'Eastern Corridor & Campus Route',
				'_bl_demographic'   => 'Academic & Growth Corridor',
				'_bl_dimensions'    => "15' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '08:00–11:00 / 15:00–19:00',
				'_bl_dwell_time'    => '45+ seconds',
				'_bl_hours'         => '11h Daily',
				'_bl_traffic_note'  => 'Campus Gateway Point',
				'_bl_lat'           => '24.9030',
				'_bl_lng'           => '91.8930',
			),
		),

		/* ---- Rangpur / Bogura / Narayanganj / Feni ---- */
		array(
			'title'    => 'Shapla Mor, Rangpur',
			'city'     => 'Rangpur',
			'hood'     => 'Shapla Mor',
			'featured' => '',
			'excerpt'  => "Rangpur's central circle — the divisional capital of the north on one screen, 100,000+ daily movements.",
			'content'  => "<p>Shapla Mor is Rangpur's reference point: the circle where the division's administration, education, and commerce intersect. Whatever moves in the northern division eventually rounds this junction.</p><p>National brands open the Rangpur market here — one placement, the whole city's attention.</p>",
			'meta'     => array(
				'_bl_impressions'   => '100,000+',
				'_bl_total_traffic' => '3M+ / month',
				'_bl_gender_split'  => '63% Male / 37% Female',
				'_bl_age_groups'    => '18–44 core (68%)',
				'_bl_professions'   => 'Officials, Traders, Students',
				'_bl_exposure'      => '4–6 plays / stop',
				'_bl_facing'        => 'Central Circle, All Approaches',
				'_bl_demographic'   => 'Divisional Capital Flow',
				'_bl_dimensions'    => "17' x 11'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '10:00–13:00 / 16:00–20:00',
				'_bl_dwell_time'    => '55+ seconds',
				'_bl_hours'         => '10h Daily',
				'_bl_traffic_note'  => 'City Centre Circle',
				'_bl_lat'           => '25.7558',
				'_bl_lng'           => '89.2444',
			),
		),
		array(
			'title'    => 'Police Plaza, Bogura',
			'city'     => 'Bogura',
			'hood'     => 'Circuit House',
			'featured' => '',
			'excerpt'  => "The administrative face of North Bengal's trade capital — Circuit House traffic and Bogura's business core.",
			'content'  => "<p>Facing the Circuit House, this screen reads to Bogura's administrative and business leadership — the district that anchors North Bengal's agro-trade economy.</p><p>Agri-inputs, banking, and machinery brands talk to their actual buyers here, in the city where those buying decisions are made.</p>",
			'meta'     => array(
				'_bl_impressions'   => '90,000+',
				'_bl_total_traffic' => '2.7M+ / month',
				'_bl_gender_split'  => '66% Male / 34% Female',
				'_bl_age_groups'    => '25–54 core (66%)',
				'_bl_professions'   => 'Officials, Agro-Traders, Bankers',
				'_bl_exposure'      => '4–6 plays / stop',
				'_bl_facing'        => 'Circuit House Axis',
				'_bl_demographic'   => 'District Business Class',
				'_bl_dimensions'    => "16' x 9'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '09:00–12:00 / 16:00–20:00',
				'_bl_dwell_time'    => '55+ seconds',
				'_bl_hours'         => '12h Daily',
				'_bl_traffic_note'  => 'Administrative Axis Screen',
				'_bl_lat'           => '24.8466',
				'_bl_lng'           => '89.3773',
			),
		),
		array(
			'title'    => 'Chashara Crossing, Narayanganj',
			'city'     => 'Narayanganj',
			'hood'     => 'Chashara',
			'featured' => '',
			'excerpt'  => "The knitwear capital's central crossing — factory owners, port trade, and Dhaka's industrial satellite in one frame.",
			'content'  => "<p>Narayanganj makes the country's knitwear and moves much of its river trade, and Chashara is where that economy crosses paths daily — factory owners, buyers' agents, and a workforce a quarter-million strong.</p><p>The screen faces the Fotulla corridor, putting B2B and mass-consumer brands alike in front of the industry that exports for the nation.</p>",
			'meta'     => array(
				'_bl_impressions'   => '120,000+',
				'_bl_total_traffic' => '3.6M+ / month',
				'_bl_gender_split'  => '67% Male / 33% Female',
				'_bl_age_groups'    => '18–44 core (70%)',
				'_bl_professions'   => 'Factory Owners, Buyers, Workers',
				'_bl_exposure'      => '5–7 plays / stop',
				'_bl_facing'        => 'Fotulla Corridor',
				'_bl_demographic'   => 'Industrial Economy Flow',
				'_bl_dimensions'    => "16' x 10'",
				'_bl_resolution'    => 'P6 Outdoor',
				'_bl_brightness'    => '5,000 nits',
				'_bl_peak_hours'    => '08:00–10:30 / 17:00–20:30',
				'_bl_dwell_time'    => '60+ seconds',
				'_bl_hours'         => '12h Daily',
				'_bl_traffic_note'  => 'Industrial Hub Crossing',
				'_bl_lat'           => '23.6238',
				'_bl_lng'           => '90.5000',
			),
		),
		array(
			'title'    => 'Feni City Indoor Network, 188 Screens',
			'city'     => 'Feni',
			'hood'     => 'Feni City',
			'featured' => '',
			'excerpt'  => 'One buy, 188 screens — saturation coverage of an entire district city through its indoor display network.',
			'content'  => "<p>The Feni network flips the billboard model: instead of one big screen on one corner, 188 indoor displays thread through the city's shops, markets, and gathering points. Coverage isn't a corridor — it's the whole town.</p><p>For distribution-led brands, it's the rare buy where 'everywhere' is the literal product description.</p>",
			'meta'     => array(
				'_bl_impressions'   => '250,000+ network-wide',
				'_bl_total_traffic' => '7.5M+ / month',
				'_bl_gender_split'  => '60% Male / 40% Female',
				'_bl_age_groups'    => '18–54 core (74%)',
				'_bl_professions'   => 'Shoppers, Traders, Townspeople',
				'_bl_exposure'      => 'Saturation: 188 simultaneous screens',
				'_bl_facing'        => 'City-Wide Indoor Points',
				'_bl_demographic'   => 'Whole-City Coverage',
				'_bl_dimensions'    => '188-Screen Indoor Mesh',
				'_bl_resolution'    => 'HD Indoor Panels',
				'_bl_brightness'    => 'Indoor-Optimised',
				'_bl_peak_hours'    => '10:00–21:00',
				'_bl_dwell_time'    => 'In-store browse time',
				'_bl_hours'         => '12h Daily',
				'_bl_traffic_note'  => 'District Saturation Network',
				'_bl_lat'           => '23.0159',
				'_bl_lng'           => '91.3976',
			),
		),
	);
}
